### ISSUE TITLE
Will you be making a 1.19.2 version of this mod?

### ISSUE THREAD

**Issue by metalmint** [Commoble/infiniverse_utils#1]
I've got a modpack I'm working on right now and I need to be able to have the ability to add or remove dimensions and so on, could you please consider making a 1.19 version? I don't wanna have to reinvent the wheel and make a 1.19.2 version just for this

**Comment by Commoble** [comment]
1.19 made it very difficult to make dimensions with different seeds, which makes this mod much less useful

In the meantime you can add extra dimensions using dimension jsons <https://minecraft.fandom.com/wiki/Custom_dimension>
